### ISSUE TITLE
Add player.captures

### ISSUE THREAD

**Issue by Detect** [Molesmalo/StarWarsMod4AirMash#13]
Flag `.captures` stored on player objects would be helpful to implement Detect/swam_extensions#6. It can be retrieved/saved from the `detailedScoreUpdate` event in `SWAM.updatePlayerCounters` or elsewhere.

**Comment by Molesmalo** [comment]
Done. Will be up on next update. But be aware that `SWAM.updatePlayerCounters` is now just doing `Network.getScores();`.  The data is assigned upon the arrival of the detailed update (so, it's async).
