### ISSUE TITLE
request: please provide unminified (i.e. original) source code

### ISSUE THREAD

**Issue by aaronjanse** [Molesmalo/StarWarsMod4AirMash#2]
Thanks for writing this!

I'd love to contribute and it'd be a big help if the original source code is available.

**Comment by Molesmalo** [comment]
Hi! I'll see what can be done.  There are some parts of the code injected in the game's code, and I'm trying to respect the dev's decision of not releasing an unminified version (as i had replaced some variable names to make it more understandable).

I'll try to decouple it more, and then release the mod's code. But sadly, there are some parts that I just didn't see any other way of doing it, than getting in the middle of the game code.

**Comment by aaronjanse** [comment]
Ah, okay, that makes sense. Thanks for tje.mod, btw; it's super helpful and fun.

I'll close this issue, but feel free to open it back up of you want

**Comment by clark-stevenson** [comment]
@Molesmalo Hey 👍  With the official game seemingly abandoned,  would you reconsider this ticket? I have been toying with the airmash-refugee pristine code for 2 years on and off rewriting in Typescript without JQuery but it kind of sucks in certain places.  It's more of a reference than anything else.

Anyway can't believe it's 5 years old already, where has the half decade gone!

Cheers.

**Comment by clark-stevenson** [comment]
@Molesmalo  Second request and update!

I gave up for a while and then started again recently with GPT and managed to refactor the OG to code to Typescript with updated PIXI, Howler, Webpack, Protocol and so on!  I need to do much more testing which isn't a problem coz I play Airmash  frequently.  However I got 5 years of Starmash (With Hitbox theme), and I just can't go back to standard airmash and "enjoy testing".  That just isn't going to happen.

Would you consider sharing only the unminified SWAM portion of the source with no OG integration even if that is purely a private GIST?

It's totally fine if not and I can draw a line under this whole thing for good.  

Cheers! 👍
