### ISSUE TITLE
Mode settings dialog can be opened multiple times

### ISSUE THREAD

**Issue by Akaryatrh** [Molesmalo/StarWarsMod4AirMash#3]
Hey!

As said in the title, It's possible to open mod settings multiple times simply by clicking the gear icon multiple times.

BTW, thx a lot of this great mod!

**Comment by Molesmalo** [comment]
Nice catch!  I didn't realize the settings button had a higher z-index 👍
Fixed!  The bugfix will be in the next version! 

Thanks!

**Comment by Akaryatrh** [comment]
You rock 👍
