### ISSUE TITLE
Some files can't be loaded

### ISSUE THREAD

**Issue by Akaryatrh** [Molesmalo/StarWarsMod4AirMash#4]
On latest Chrome (64.0.3282.140), somes files are not loaded:
- `styles.css` is not loaded because of its wrong mime-type
- `map.json` because of a bad request response

![capture d ecran 2018-02-08 a 13 34 18](https://user-images.githubusercontent.com/574787/35973210-df4cf9f0-0cd4-11e8-90e4-427481dbb260.png)

**Comment by Molesmalo** [comment]
Oh!  Sorry for the delay, I haven't updated this repo for a few days and didn't see this.   I'll upload later a working config file! Sorry again.

**Comment by Molesmalo** [comment]
1- Download this file:
https://molesmalo.github.io/StarWarsMod4AirMash/redirect_rules/requestly_rules.txt

2- Open Requestly's config panel (click on Requestly's icon to open it)
3- Delete previous rules in Requestly (select all rules, and click the trash bin icon)
4- Upload this config file.
5- Go to the game's page, and do a hard refresh  (ctrl-f5 in windows)

This should make it work.
Cya!

**Comment by Akaryatrh** [comment]
Thx, it's working great again 👍
