### ISSUE TITLE
Howler.js bug

### ISSUE THREAD

**Issue by fabiospampinato** [Molesmalo/StarWarsMod4AirMash#5]
Hey, I didn't find you anymore in the game, so here's a quick update:

I've removed the redirect entry from requestly, replaced `assets/sounds.mp3?4` with `https://airma.sh/assets/sounds.mp3` and it still works for me. But if I do replace it with `http://localhost:4444/assets/sounds.mp3` I'm still getting some sounds but overall it's kind of broken, there are some unrelated sounds playing all the time.

So I thought there might be a problem with cross-origin requests, but I haven't found this mentioned in any of Howler.js' commits.

I'll look into this more in depth tomorrow.

In the meantime let me know if the base64 workaround works, [here](https://staxmanade.com/2015/11/how-to-base64-and-save-a-binary-audio-file-to-local-storage-and-play-it-back-in-the-browser/) they might have a possible implementation of this (basically `fetch` the file, get its content, then encode it to base64). I'd do this steps:
1. Manually base64 encode the file (don't forget to add the "data:audio" (or whatever it is) prefix to the string) and put it in the `src` array.
2. If that works, leave the `src` array empty, hardcode the base64 string in the source and try to "inject" it dynamically.
3. If that works, actually load the file and encode it in the browser.

Good luck :+1:

**Comment by Molesmalo** [comment]
The solution was to preserve the https protocol for the sounds file. It the file is served via http, the sound sprites keep playing until EOF.

In my case, while developing, it also meant serving it using https from localhost...
