### ISSUE TITLE
Extensions Repository Ideas

### ISSUE THREAD

**Issue by Molesmalo** [Molesmalo/StarWarsMod4AirMash#7]
Hey, I wanted to ask what you think would be the best way for implementing a simple directory for extensions.

I've been thinking on a small node app , so having js we can test the extension's url loads and registers successfuly, and checking if the file is valid. Ideally, it would be hosted on the free tier on some cloud service. (like [this](https://www.openshift.com/pricing/index.html))

Then the app would provide an api for crud.  The ui could be rendered serverside (and embebed by the mod) or client-side (and making just the ajax calls). 

Storage could be a simple nosql db, sqlite, MySQL or whatever is available on the hosting.

Opinions?

**Comment by Detect** [comment]
Are there any open source registry code we could use?

**Comment by fabiospampinato** [comment]
A few random ideas:

- **Basic**: keeping track of all the available extensions in a JSON file should be enough. Getting a list of all the available extensions would mean retrieving this file and adding/removing extensions would simply be a matter of editing it.
- **Fun**: a repository on github managed by a bot that accepts all (sane) PRs, the file system will kind-of be our database.
- **Proper registry**: tell extensions authors to publish them on NPM with a particular keyword in their `package.json` file, something like `swam-extension`. This way we could find extensions just by searching for `swam-extension` in NPM and there would be no need to deal with hosting, versioning etc.

**Comment by Detect** [comment]
I'm in favor of the simplicity of Moz's basic option (extensions in JSON file) for now, so we can spend more time on the mod and extensions themselves.
